[workspace]
resolver = "3"
members = [
    "crates/schooner-engine",
    "crates/game-void",
    "crates/bench-ecs",
]

[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MuirDun/schooner"

[workspace.dependencies]
wgpu = "29"
winit = "0.30"
glam = "0.32"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
log = "0.4"
env_logger = "0.11"
thiserror = "2"
anyhow = "1"
criterion = { version = "0.8", default-features = false, features = ["plotters", "cargo_bench_support"] }
egui = { version = "0.34", default-features = false, features = ["default_fonts"] }
egui-winit = { version = "0.34", default-features = false }
egui-wgpu = { version = "0.34", default-features = false }
puffin = "0.20"

schooner-engine = { path = "crates/schooner-engine" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
