[package]
name = "game"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
schooner-engine.workspace = true
anyhow.workspace = true
log.workspace = true
glam.workspace = true
subsecond = { version = "0.7.9", optional = true }
dioxus-devtools = { version = "0.7.9", optional = true }

[features]
hot = ["dep:subsecond", "dep:dioxus-devtools"]
